spring:
  application:
    name: springcloud-alibaba-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.209.129:8848
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
server:
  port: 9090

dubbo:
  scan:
    # dubbo ?????
    base-packages: com.example.microservicedemoproviderservice.service
  protocol:
    # ?????dubbo
    name: dubbo
    # dubbo ???? ?-1 ????????20880???
    port: -1
  registry:
    # ?????????nacos?????
    address: spring-cloud://192.168.209.129
  cloud:
    subscribed-services:microservice-demo-provider,microservice-demo-consumer
